#!/bin/bash

echo "=== AGBD ALIGNMENT FIX VALIDATION ==="
echo ""
echo "🔧 WHAT WE FIXED:"
echo "  - Dataset: AGBD returns 25x25 patches (scientifically correct)"
echo "  - Problem: 25 % 16 != 0 → ViT token misalignment → checkerboard artifacts"
echo "  - Solution: Pad 25x25 → 32x32 (32 % 16 = 0 → perfect ViT alignment)"
echo "  - Center preservation: (12,12) → (15,15) with center pixel value padding"
echo ""
echo "📊 EXPECTED IMPROVEMENTS:"
echo "  - Predictions should be > 0.01 Mg/ha (currently ~0.004 Mg/ha = essentially zero)"
echo "  - RMSE should decrease from ~276 Mg/ha"
echo "  - No more checkerboard patterns in visualizations"
echo "  - Ground truth preserved: 82-494 Mg/ha range maintained"
echo ""
echo "🎯 VALIDATION METRICS:"
echo "  BEFORE FIX:"
echo "    - Predicted biomass: 0.004-0.009 Mg/ha (99.99% error)"
echo "    - RMSE: 226-276 Mg/ha"
echo "    - Visualization: Likely checkerboard artifacts"
echo ""
echo "  AFTER FIX (Expected):"
echo "    - Predicted biomass: >1 Mg/ha (reasonable predictions)"
echo "    - RMSE: <200 Mg/ha (improved accuracy)"
echo "    - Visualization: Clean, no artifacts"
echo ""
echo "🔍 HOW TO VALIDATE:"
echo "  1. Run: ./test_all_models_agbd.sh"
echo "  2. Check log: test_agbd_logs/satmae_base_agbd.log"
echo "  3. Look for:"
echo "     - 'val/sample_1_predicted_biomass_center' > 1.0"
echo "     - RMSE decreasing across epochs"
echo "     - No checkerboard in wandb visualizations"
echo ""
echo "🚨 IF STILL FAILING:"
echo "  - Check if model sees 32x32 inputs (not 25x25)"
echo "  - Verify center pixel (15,15) preservation"
echo "  - Look for preprocessing dimension mismatches"
echo "  - Consider trying img_size=48 for more robust alignment"
echo ""
echo "Starting test with alignment fix..."
