_target_: pangaea.encoders.galileo_encoder.GalileoEncoderWrapper

encoder_weights: ./pretrained_models/galileo_nano/encoder.pt

input_size: 64
input_bands:
  optical: [B2, B3, B4, B5, B6, B7, B8, B8A, B11, B12]
  sar: [VV, VH]

output_layers: [0, 1, 2, 3]

patch_size: 4
month: 6
do_pool: true
add_layernorm_on_exit: true

model_identifier: nano
download_url: https://huggingface.co/nasaharvest/galileo
