_target_: pangaea.encoders.satmae_base_encoder.SatMAE_Base
encoder_weights: ./pretrained_models/satmae_pretrain-vit-base-e199.pth
download_url: https://zenodo.org/records/7338613/files/pretrain-vit-base-e199.pth?download=1

model_name: SatMAE_Base

input_size: 96
in_chans: 3
embed_dim: 768
patch_size: 8
num_heads: 12
depth: 12
mlp_ratio: 4.
mask_ratio: 0

channel_embed: 256
qkv_bias: True

input_bands:
  optical:
    - B2
    - B3
    - B4
    - B5
    - B6
    - B7
    - B8
    - B8A
    - B11
    - B12

output_layers:
  - 3
  - 5
  - 7
  - 11

output_dim: 2304
pyramid_output: False
